### ISSUE TITLE
Unable to pre-dex exception

### ISSUE THREAD

**Issue by MFlisar** [frankiesardo/icepick#105]
I'm getting following error in my project:

```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: 
Unable to pre-dex 'C:\Users\Michael\.gradle\caches\modules-2\files-2.1\frankiesardo\icepick-processor\3.2.0\bcbd91021882bd042a36931ad0e8f835a72a5475\icepick-processor-3.2.0.jar' 
to 
'M:\dev\libraries\RecyclerViewPreferences\app\build\intermediates\pre-dexed\debug\icepick-processor-3.2.0_055437a1e11522bf02b4bc1382e0b993ffd01814.jar'
```

Any ideas why? I have other annotation processors in my library and all work fine. Icepick is even generating files successfully if I build the project, but if I try to run it I get the above exception ...

Any ideas?

I'm using android studio 2.3.3 and gradle 2.3.3 (both are the newest release versions) and following:

    compile 'frankiesardo:icepick:3.2.0'
    annotationProcessor  'frankiesardo:icepick-processor:3.2.0'here

**Comment by MFlisar** [comment]
Sorry, found it... With this library annotationProcessor is not working...

**Comment by jhz-zhangyun** [comment]
How do you solve that?
