### ISSUE TITLE
Any chance to release under Apache-2.0 ???

### ISSUE THREAD

**Issue by StephanSchuster** [frankiesardo/icepick#111]
Icepick is released under EPL-1.0. According to our legal department, this means that any Android project which uses Icepick needs to be open sourced as well. :-(

Reason: In general Android projects "statically link" their dependencies (like Icepick). In the compiled APK these dependencies are therefore no more identifiable as "separate modules" which in turn enforces you to open source the code that uses the EPL-1.0 project (e.g. Icepick) even if it has not been modified at all but just been used as intended by the author.

Is this correct?
Is Icepick using EPL-1.0 intentionally (e.g. for the above reason)?

Is there any chance to release under Apache-2.0 instead of EPL-1.0 ???

Thank you!

**Comment by tomblenz** [comment]
Your legal dept is wrong - EPL 1.0 is "weak copyleft", you only need to provide the source to icepick (if you change it).  Maybe get a new legal dept :)

https://tldrlegal.com/license/eclipse-public-license-1.0-(epl-1.0)

https://stackoverflow.com/questions/4925638/can-epl-eclipse-public-licence-be-used-in-commercial-context

https://www.whitesourcesoftware.com/whitesource-blog/eclipse-public-license-questions-answered/
