### ISSUE TITLE
Remove "Note: IcepickProcessor took X milliseconds"

### ISSUE THREAD

**Issue by pieces029** [frankiesardo/icepick#26]
Not a big deal, but I find this text annoying building. Maybe only have it in debug version of the library? If you don't agree, again NBD, just a though.

Also, thanks for building this and your blog post about building it. It inspired me to make my own Annotation Processor.

**Comment by frankiesardo** [comment]
Fixed with 460e7c82690977dea7e46be474567298b92a3da4
