### ISSUE TITLE
Support null values

### ISSUE THREAD

**Issue by MichaelFlisar** [frankiesardo/icepick#31]
I would suggest, that you generate code like following (example for Long, but should be used for all objects):

Saving:

    if (target.icon != null)
        outState.putLong(BASE_KEY + "icon", target.icon);

Reading:

    if (savedInstanceState.containsKey(BASE_KEY + "icon"))
        target.icon =  savedInstanceState.getLong(BASE_KEY + "icon");

Otherwise, you library which is really very useful, can't be used with null values...

**Comment by clemp6r** [comment]
Any update?

**Comment by frankiesardo** [comment]
If @Alexander-- is not interested anymore in his PR, I will fix it on the fly myself. Expect a snapshot version soon(ish).

**Comment by frankiesardo** [comment]
Pushed a `2.3.7-SNAPSHOT` artefact. It should just work now.
