### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by ming13** [frankiesardo/icepick#37]
Is it possible to host the Icepick at the Maven Central instead (or as well as) of Clojars?

**Comment by frankiesardo** [comment]
Not as easy as it looks like. I'm using mustache for easy template rendering, thus adding an external dependency that is hosted in Clojars.

It's a one-liner to add clojars repo to your gradle builds and it's easy if you use Maven as well. If that becomes an issue I might consider dropping mustache templating.

I'll leave this issue open for discussion.

**Comment by ming13** [comment]
Well, you are right, it is not too hard. Group ID change and manual repository resolving confused me a bit. Personally I just don’t like the idea of a possible situation when every library forces repository declaration. Plus, reliability of Clojars is not as great as Central (only theoretically of course, there is no doubt that Clojars is totally fine and stable). Your call anyway!

**Comment by jenzz** [comment]
+1 for Maven Central or JCenter :+1:

**Comment by ragunathjawahar** [comment]
+1 for a centralized repo.

**Comment by sockeqwe** [comment]
+1 :+1:

**Comment by Wavesonics** [comment]
+1

**Comment by frankiesardo** [comment]
I see many benefits of using clojars (accessing all clojure libraries, artefacts instantly available, no manual steps required and my setup publishes snapshots on every commits, etc.).

Moving to Maven means reimplementing mustache templating manually or switching to something inferior, potentially adding bugs to the library.

If there are no other reasons on the users side rather than "I don't want to add a one-liner to my Gradle build file" then no matter how many +, it is not moving away from Clojars anytime soon.

**Comment by ming13** [comment]
My initial personal concern was more about unification than against Clojars. There is already some controversy about repositories and it starts to disturb me. We already have Maven Central, jCenter (which actually tries to superset Central), Clojars, JitPack and so on. But I must say it is not anyone’s fault, maybe Central apply rules are kind of outdated and complex too much, which causes portion of the trouble.

Anyway, I don’t see any technical reasons to move to Central. Maybe resolution time is a bit longer with Clojars applied?

I’m closing the issue, feel free to reopen it if you have any technical concerns like @frankiesardo said.

**Comment by ming13** [comment]
A side effect of using Clojure is messing APK a little. There are some files embedded in the package which we clearly don’t want to have.

* `project.clj`
* `META-INF/leiningen/frankiesardo/icepick/project.clj`

Yes, it is is possible to configure `android.packagingOptions.exclude`. Yes, it is not a biggie. But this and additional repository declaration in each project is kind of annoying.

And yes, Java is “boring” and so on, but [JavaPoet](https://github.com/square/javapoet) is not that bad. Just saying.

**Comment by frankiesardo** [comment]
It shouldn't be too hard to exclude those files from icepick jars, let me have a look.

If done properly nobody should be able to tell a Clojure jar from a Java one. Just saying :octocat:

**Comment by ming13** [comment]
Agreed! :sparkles:

**Comment by frankiesardo** [comment]
Fixed in 3b6ab145b6d3b949553accbbc3198f124327fd3a

**Comment by ming13** [comment]
Thanks!
