### ISSUE TITLE
Support for Parceler, use getters and setters

### ISSUE THREAD

**Issue by johnjohndoe** [frankiesardo/icepick#38]
I use POJOs with [*Jackson* annotations](https://github.com/FasterXML/jackson-annotations) and [*Parceler*](https://github.com/johncarl81/parceler) for my client model. Such a class looks like this:

```java
@Parcel
public class Properties {

    @JsonProperty("product")
    private String product;

    @JsonProperty("product")
    public String getProduct() {
        return product;
    }

    @JsonProperty("product")
    public void setProduct(String product) {
        this.product = product;
    }

}
```

When I let *Icepick* handle the instance state the following error occurs:

> Parceler: Reflection is required to modify private field: String product, consider using non-private.

Do you know why this is happening?

**Comment by frankiesardo** [comment]
Which version of `icepick` are you using?

**Comment by johnjohndoe** [comment]
3.0.0 via clojars.org

**Comment by frankiesardo** [comment]
I'm assuming if you don't use icepick and do the calls to Bundle manually with the same POJO you don't get any error, right?

Can you post the code invocation that fails?

**Comment by johnjohndoe** [comment]
Correct. Without *Icepick* I do:

```java
outState.putParcelable(BundleKeys.SELECTED_PROPERTIES, Parcels.wrap(mProperties));
```
and
```java
Parcelable parcelable = savedInstanceState.getParcelable(BundleKeys.SELECTED_PROPERTIES);
mProperties = Parcels.unwrap(parcelable);
```

**Comment by frankiesardo** [comment]
And how do you do with icepick?
`@Icicle Properties  mProperty` should fail to compile because `Property` does not implement `Parcelable`

**Comment by johnjohndoe** [comment]
True. It feels as if *Icepick* and *Parceler* have to get married. It would probably work if I could pass a *Parcelable* to *Icepick* ...

```java
public static <T> android.os.Parcelable saveInstanceState(T t, android.os.Parcelable parcelable)
```
... such as here:

```java
Icepick.saveInstanceState(this, Parcels.wrap(mProperties));
```
But then I still could not use the `@Icicle` annotation. Something magic like `@Icicle(use=Parceler)` would be nice.

**Comment by frankiesardo** [comment]
Here's the discussion relative to Parceler and why I support AutoParcel as a better alternative. https://github.com/frankiesardo/icepick/pull/20

If you use AutoParcel Icepick will work out of the box. I think you could use the new AutoValue Builder feature for Jackson/Gson support.

BTW did your code fail to compile as I said? If not please let me know because that would be an icepick bug.

**Comment by johnjohndoe** [comment]
No unforeseen error. After I removed the `private` qualifier for the `@Icicle` annotated member the following error occurs for good reasons:

> Error:(95, 15) error: Don't know how to put a com.example.Product inside a Bundle

**Comment by frankiesardo** [comment]
Cool. If you're willing to try out AutoParcel and need help in setting it up let me know.

**Comment by johnjohndoe** [comment]
Thank you for pointing me at #20 - I just read through the issue. I do not have time to integrate *[AutoParcel](https://github.com/frankiesardo/auto-parcel)* right now but I put it on my TODO list. Thank you for your time.

**Comment by johncarl81** [comment]
@johnjohndoe FYI, I have a fork of Icepick that works as you describe with Parceler here: https://github.com/johncarl81/icepick/tree/parceler_support.  Looks like I need to rebase onto the newest clojure branch.

**Comment by frankiesardo** [comment]
@johncarl81 version 3.0.0 fixes some bugs, but the previous version you're based on should still be usable. You could use this as a great opportunity to step up your Clojure game! Ping me if you have any questions

**Comment by johncarl81** [comment]
@frankiesardo that's what I was thinking.  Will do, Thanks!

**Comment by johnjohndoe** [comment]
@johncarl81 Thanks for the note.
