### ISSUE TITLE
Fragment Support

### ISSUE THREAD

**Issue by ZakTaccardi** [frankiesardo/icepick#39]
Does Icepick work with Fragments?

Or is it an activity/view only thing?

**Comment by frankiesardo** [comment]
Yes it does work with Fragment or any other object.
Views have a different instance state logic and are supported as well.

**Comment by jenzz** [comment]
It would be nice to include an example implementation for `Fragments` in the README for the sake of completeness.

**Comment by frankiesardo** [comment]
Made it clearer with 0d7706e51c3b7bbaf179d5c5f86a7c93f4622b3a
