### ISSUE TITLE
Typo in Injector Helper in getByteArray

### ISSUE THREAD

**Issue by xsveda** [frankiesardo/icepick#40]
There is a typo on line 70 in https://github.com/frankiesardo/icepick/blob/master/icepick/src/icepick/Injector.java

![typo](https://cloud.githubusercontent.com/assets/7130807/6283567/9df6afa4-b8e6-11e4-9367-ff700347d792.PNG)

Byte arrays are not possible to restore.

**Comment by frankiesardo** [comment]
Snap! Thanks for catching that.

**Comment by xsveda** [comment]
Thanks for such a quick fix!!!!!!
Will you create a bugfix release? This issue is kind of a blocker for me right now :-)

**Comment by frankiesardo** [comment]
Published `3.0.1-SNAPSHOT`. Will make an official release soonish.

**Comment by xsveda** [comment]
SNAPSHOT works, amazing! :+1:
