### ISSUE TITLE
Injector's Helper limits ParcelableArrayList and SparseParcelableArray to Parcelable type only

### ISSUE THREAD

**Issue by xsveda** [frankiesardo/icepick#41]
Methods `putParcelableArrayList()` and `putSparseParcelableArray()` should support also classes that inherits from `Parcelable`, same as appropriate getters do.
![parcelable](https://cloud.githubusercontent.com/assets/7130807/6288571/2fa815c2-b91a-11e4-9097-5f96a2868d42.PNG)

**Comment by frankiesardo** [comment]
:+1:
