### ISSUE TITLE
Injector reports errors into logcat while everything is ok

### ISSUE THREAD

**Issue by konmik** [frankiesardo/icepick#42]
https://github.com/frankiesardo/icepick/blob/614c495b9b63a2d6995e2f545889391fd28baa2d/icepick/src/icepick/Injector.java#L358

and

https://github.com/frankiesardo/icepick/blob/614c495b9b63a2d6995e2f545889391fd28baa2d/icepick/src/icepick/Injector.java#L363

**Comment by frankiesardo** [comment]
There you go, that's what happens when you don't remove logs after debugging. Thanks for spotting this
