### ISSUE TITLE
Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by RobbySmet** [frankiesardo/icepick#46]
Hi,

I get an error when I try to run my application. 

Information:Gradle tasks [:app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:library:compileLint
:library:copyReleaseLint UP-TO-DATE
:library:preBuild UP-TO-DATE
:library:preReleaseBuild UP-TO-DATE
:library:checkReleaseManifest
:library:preDebugAndroidTestBuild UP-TO-DATE
:library:preDebugBuild UP-TO-DATE
:library:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:library:prepareReleaseDependencies
:library:compileReleaseAidl UP-TO-DATE
:library:compileReleaseRenderscript UP-TO-DATE
:library:generateReleaseBuildConfig UP-TO-DATE
:library:generateReleaseAssets UP-TO-DATE
:library:mergeReleaseAssets UP-TO-DATE
:library:generateReleaseResValues UP-TO-DATE
:library:generateReleaseResources UP-TO-DATE
:library:mergeReleaseResources UP-TO-DATE
:library:processReleaseManifest UP-TO-DATE
:library:processReleaseResources UP-TO-DATE
:library:generateReleaseSources UP-TO-DATE
:library:compileReleaseJava UP-TO-DATE
:library:extractReleaseAnnotations UP-TO-DATE
:library:mergeReleaseProguardFiles UP-TO-DATE
:library:processReleaseJavaRes UP-TO-DATE
:library:packageReleaseJar UP-TO-DATE
:library:compileReleaseNdk UP-TO-DATE
:library:packageReleaseJniLibs UP-TO-DATE
:library:packageReleaseLocalJar UP-TO-DATE
:library:packageReleaseRenderscript UP-TO-DATE
:library:packageReleaseResources UP-TO-DATE
:library:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72200Library UP-TO-DATE
:app:prepareComAndroidSupportPaletteV72200Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72200Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:app:prepareComDaimajiaAndroidanimationsLibrary113Library UP-TO-DATE
:app:prepareComDaimajiaEasingLibrary100Library UP-TO-DATE
:app:prepareComMcxiaokeViewpagerindicatorLibrary241Library UP-TO-DATE
:app:prepareComNispokSnackbar2106Library UP-TO-DATE
:app:prepareGinsonlineLibraryUnspecifiedLibrary UP-TO-DATE
:app:prepareJpWasabeefRecyclerviewAnimators113Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJava UP-TO-DATE
:app:preDexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.util.ExceptionWithContext: no mapping specified for register
	at com.android.dex.util.ExceptionWithContext.withContext(ExceptionWithContext.java:45)
	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:369)
	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:137)
	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:93)
	at com.android.dx.command.dexer.Main.processClass(Main.java:729)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
Caused by: java.lang.RuntimeException: no mapping specified for register
	at com.android.dx.ssa.BasicRegisterMapper.map(BasicRegisterMapper.java:63)
	at com.android.dx.ssa.SsaInsn.mapRegisters(SsaInsn.java:159)
	at com.android.dx.ssa.SsaMethod.mapRegisters(SsaMethod.java:394)
	at com.android.dx.ssa.back.SsaToRop.moveParametersToHighRegisters(SsaToRop.java:235)
	at com.android.dx.ssa.back.SsaToRop.convert(SsaToRop.java:118)
	at com.android.dx.ssa.back.SsaToRop.convertToRopMethod(SsaToRop.java:69)
	at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:101)
	at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:72)
	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:297)
	... 15 more
...while processing invoke (Ljava/lang/Object;)Ljava/lang/Object;
...while processing stencil/ast$fn__389.class
1 error; aborting
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1

project build.gradle file: http://pastebin.com/rVZj2bwA
module build.gradle file: http://pastebin.com/3aXNH5WT

I also updated my JDK (from 1.7.0_60 to 1.8.0_40), but I'm still getting the same error.. 
Any idea how I can fix this?

**Comment by frankiesardo** [comment]
I think you added the processor as a compile dependency. You should ad it as 'provided', (se in the [README](https://github.com/frankiesardo/icepick/blob/master/README.md#download)).

**Comment by RobbySmet** [comment]
Damn, you're right. Stupid mistake.. Thanks for the quick reply!

**Comment by SavAcharya** [comment]
Use this ..worked for me

defaultConfig {        
    // Enabling multidex support.
    multiDexEnabled true
}

**Comment by Everdes** [comment]
Thanks SavAcharya, you saved my life...

**Comment by tranmyan** [comment]
Thank frankiesardo, works for me

**Comment by ASAIK** [comment]
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_65\bin\java.exe'' finished with non-zero exit value 1

please help me

**Comment by gearoof** [comment]
don forget to clean project and rebuild project,,,

**Comment by dosoos** [comment]
i see the error, very hard

**Comment by kiddodhaval** [comment]
I have an error which states 
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: bolts/AggregateException.class

any idea how to resolve this?

**Comment by jacky1234** [comment]
@kiddodhaval I have the same problem with you ,have you solved it?

**Comment by PaijoRX** [comment]
Thanks SavAcharya, you saved my life.

**Comment by hnxzlxf** [comment]
Error:Execution failed for task ':BaseProject:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android-sdk-windows\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1
Information:BUILD FAILED

clean-rebuild,no use...who can help me?

**Comment by jacky1234** [comment]
可能是app和依赖module中存在同一个lib引用引起的（删除了其中一个android-support-v4.jar解决问题了）
perhaps your app  and the module you dependency has the same lib,remove one.it helped me.




------------------ 原始邮件 ------------------
发件人: "hnxzlxf";<notifications@github.com>;
发送时间: 2016年3月8日(星期二) 晚上6:12
收件人: "frankiesardo/icepick"<icepick@noreply.github.com>; 
抄送: "御剑飞来"<847564732@qq.com>; 
主题: Re: [icepick] Process 'command 'C:\ProgramFiles\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1(#46)




Error:Execution failed for task ':BaseProject:processReleaseResources'.
  
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android-sdk-windows\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1
 Information:BUILD FAILED
  
clean-rebuild,no use...who can help me?

**Comment by hnxzlxf** [comment]
刚才注销了这个 //compile "com.android.support:support-v4:${supportVersion}"
apply plugin: 'com.android.library'

ext {
    supportVersion = '23.2.0'
}

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    //compile "com.android.support:support-v4:${supportVersion}"
    compile "com.android.support:appcompat-v7:${supportVersion}"
    compile "com.android.support:recyclerview-v7:${supportVersion}"
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.google.zxing:core:3.2.1'
    compile 'com.github.bumptech.glide:glide:3.6.1'
}

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }

        // Move the tests to tests/java, tests/res, etc...
        instrumentTest.setRoot('tests')

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the main source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.
        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 19
    }
}

**Comment by jacky1234** [comment]
did it work?  have any same lib on your main project and dependencies library?



------------------ 原始邮件 ------------------
发件人: "hnxzlxf";<notifications@github.com>;
发送时间: 2016年3月8日(星期二) 晚上6:22
收件人: "frankiesardo/icepick"<icepick@noreply.github.com>; 
抄送: "御剑飞来"<847564732@qq.com>; 
主题: Re: [icepick] Process 'command 'C:\ProgramFiles\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1(#46)




刚才注销了这个 //compile "com.android.support:support-v4:${supportVersion}"
 apply plugin: 'com.android.library'
 
ext {
     supportVersion = '23.2.0'
 }
 
dependencies {
     compile fileTree(include: '*.jar', dir: 'libs')
     //compile "com.android.support:support-v4:${supportVersion}"
     compile "com.android.support:appcompat-v7:${supportVersion}"
     compile "com.android.support:recyclerview-v7:${supportVersion}"
     compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
     compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0'
     compile 'com.squareup.okhttp:okhttp:2.4.0'
     compile 'com.squareup.retrofit:retrofit:1.9.0'
     compile 'com.google.zxing:core:3.2.1'
     compile 'com.github.bumptech.glide:glide:3.6.1'
 }
 
android {
     compileSdkVersion 23
     buildToolsVersion '23.0.2'
     sourceSets {
         main {
             manifest.srcFile 'AndroidManifest.xml'
             java.srcDirs = ['src']
             resources.srcDirs = ['src']
             aidl.srcDirs = ['src']
             renderscript.srcDirs = ['src']
             res.srcDirs = ['res']
             assets.srcDirs = ['assets']
             jniLibs.srcDirs = ['libs']
         }
     // Move the tests to tests/java, tests/res, etc...     instrumentTest.setRoot('tests')     // Move the build types to build-types/<type>     // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...     // This moves them out of them default location under src/<type>/... which would     // conflict with src/ being used by the main source set.     // Adding new build types or product flavors should be accompanied     // by a similar customization.     debug.setRoot('build-types/debug')     release.setRoot('build-types/release') } defaultConfig {     minSdkVersion 14     targetSdkVersion 19 }  
}

**Comment by hnxzlxf** [comment]
yes.....did not work.....

**Comment by craining** [comment]
# **WHO CAN SAVE MY LIFE?**

com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\Android_Studio\sdk\build-tools\21.0.0\aapt.exe'' finished with non-zero exit value -1073741819



The log:




Executing tasks: [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :openimSDK:generateDebugSources, :openimSDK:generateDebugAndroidTestSources]

Configuration on demand is an incubating feature.
:app:clean UP-TO-DATE
:openimSDK:clean
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:openimSDK:preBuild UP-TO-DATE
:openimSDK:preReleaseBuild UP-TO-DATE
:openimSDK:compileReleaseNdk UP-TO-DATE
:openimSDK:compileLint
:openimSDK:copyReleaseLint UP-TO-DATE
:openimSDK:mergeReleaseProguardFiles UP-TO-DATE
:openimSDK:packageReleaseRenderscript UP-TO-DATE
:openimSDK:checkReleaseManifest
:openimSDK:preDebugAndroidTestBuild UP-TO-DATE
:openimSDK:preDebugBuild UP-TO-DATE
:openimSDK:preDebugUnitTestBuild UP-TO-DATE
:openimSDK:preReleaseUnitTestBuild UP-TO-DATE
:openimSDK:prepareComAndroidSupportMultidex101Library
:openimSDK:prepareReleaseDependencies
:openimSDK:compileReleaseRenderscript
:openimSDK:generateReleaseResValues UP-TO-DATE
:openimSDK:generateReleaseResources
:openimSDK:packageReleaseResources
:openimSDK:compileReleaseAidl
:openimSDK:generateReleaseBuildConfig
:openimSDK:generateReleaseAssets UP-TO-DATE
:openimSDK:mergeReleaseAssets
:openimSDK:mergeReleaseResources
:openimSDK:processReleaseManifest
:openimSDK:processReleaseResources
:openimSDK:generateReleaseSources
:openimSDK:compileReleaseJavaWithJavac
:openimSDK:processReleaseJavaRes UP-TO-DATE
:openimSDK:transformResourcesWithMergeJavaResForRelease
:openimSDK:transformClassesAndResourcesWithSyncLibJarsForRelease
:openimSDK:mergeReleaseJniLibFolders
:openimSDK:transformNative_libsWithMergeJniLibsForRelease
:openimSDK:transformNative_libsWithSyncJniLibsForRelease
:openimSDK:bundleRelease
:app:prepareComAndroidSupportMultidex101Library
:app:prepareWorkplaceOpenimSDKUnspecifiedLibrary
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
Warning: E:\Android_Studio\workplace\app\src\main\AndroidManifest.xml:23:5-68 Warning:
	Element uses-permission#android.permission.GET_TASKS at AndroidManifest.xml:23:5-68 duplicated with element declared at AndroidManifest.xml:14:5-68
:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\Android_Studio\sdk\build-tools\21.0.0\aapt.exe'' finished with non-zero exit value -1073741819

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 49.758 secs

**Comment by yolinsoft** [comment]
Delete android/app/build Folder

**Comment by qinhuangdaoStation** [comment]
my problem is caused by unmatched version

**Comment by welcometotangshan** [comment]
我遇到了相同问题，“finished with non-zero exit value 1”，现在解决了，出现的原因是Android studio自动更新某些部件时，某些配置删除了，打开窗口Project Structure -> Appname -> Build Tools Version 内容为value，修改为任意内容即可，如改为23.0.1。

**Comment by grath92** [comment]
I Reject Embedded JDK ( in 32bit ) because embedded JDK is 64bit

Right click your Project -> Open Module Setting -> SDK Location -> Uncheck Use embedded JDk then set your JDK Path, eg in Ubuntu /usr/lib/jvm/java-8-openjdk-i386

**Comment by checkming** [comment]
Here are some tips for making mistakes：
Error:ERROR: 9-patch image E:\AndroidStudioProjects\GuangTu\res\drawable-hdpi\tool_box_fragment_bg_focus.9.png malformed.
Error:Error: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Administrator\AppData\Local\Android\Sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 42
Error:Execution failed for task ':mergeDebugResources'.
> E:\AndroidStudioProjects\GuangTu\res\drawable-hdpi\tool_box_fragment_bg_focus.9.png: Error: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Administrator\AppData\Local\Android\Sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 42
-----------------------------------------------
Is it because of the.9.png? The graphics are not standard?
please help me

**Comment by sandeeplondhe** [comment]
hello i am getting the same problem , and not able to build the apk, and build is getting successful but when i try to build apk or try to run the app on device it gives me the following error.

> 
> Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@ E:\Projects\My\App\Name\app\build\intermediates\tmp\desugar_args4999816675674775397}

On further inspection in the code it gives me the following error

```
02:41:17.321 [ERROR] [com.android.build.gradle.internal.transforms.DesugarTransform] Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)


```

please let me know if anyone have the solution for it.

**Comment by karuhanga** [comment]
This issue made me pull out lots of my hair.
In my case, it turns out I had incompatible Firebase library versions.

I would suggest running through your dependencies once more for good measure, and make sure **libraries that should be the same version are**, **libraries that depend on a particular version have that version**, and you have **not redefined dependencies** that already transitively come from another dependency you have added.

**Comment by omarihamza** [comment]
@Karuhanga You saved my day bro!!
