### ISSUE TITLE
Abandoning search

### ISSUE THREAD

**Issue by fahimk** [frankiesardo/icepick#50]
I keep getting

Not found. Trying superclass android.support.v7.app.ActionBarActivity
MISS: Reached framework class. Abandoning search.

any idea what could be going on? I have pretty much the same code as the example

**Comment by frankiesardo** [comment]
Are you sure your class has an `@Icicle` annotated field?

Otherwise your setup is not processing annotations, I would recommend
reading a general annotation processing guide for your IDE and build tool.

**Comment by fahimk** [comment]
Yes, I have the @Icicle field. I'm using Android studio. Other annotation mechanisms such as fragmentargs, parcelableplease, dagger, and butterknife are all working.

I tried rebuilding/cleaning multiple times, but that wouldn't help either.

**Comment by frankiesardo** [comment]
Are the relevant `$$Icicle` classes generated then? If you can share the relevant bits of your gradle build file and the problematic class i can give you more help.

**Comment by fahimk** [comment]
Which folder do I check for the relevant $$Icicle classes? Here is what my code looks like:
```

import com.hannesdorfmann.mosby.dagger1.Injector;
import android.support.v7.app.ActionBarActivity;
public class MyActivity extends  extends ActionBarActivity implements Injector {

    @Icicle String url;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Icepick.restoreInstanceState(this, savedInstanceState);
        if(url == null) {
             url = "test";
        }
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        Icepick.saveInstanceState(this, outState);
    }
```

I set a breakpoint at url="test", and that is always being called because url is always null. I'm trying to figure out if one of the other annotation libraries is having a conflict with icepick.

**Comment by kafji** [comment]
@fahimk Do you use [android apt plugin](https://bitbucket.org/hvisser/android-apt)? If you do then you might want to check #54.

**Comment by fahimk** [comment]
That was it, thanks! @frankiesardo what do you think about updating the readme to include this?

**Comment by frankiesardo** [comment]
It seems more an issue of the `apt` plugin that conflicts with the normal `provided` scope, but a note in the README doesn't hurt either.

**Comment by Anjula** [comment]
for me, it works after changing the gradle from this

`implementation 'frankiesardo:icepick:3.2.0'`
`compileOnly 'frankiesardo:icepick-processor:3.2.0'`

to this

`implementation 'frankiesardo:icepick:3.2.0'`
`annotationProcessor 'frankiesardo:icepick-processor:3.2.0'`
