### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by IlyaEremin** [frankiesardo/icepick#53]
Hi, I am using proguard and faced with problem. Current Icepick proguard rules described here prevent from obfuscate class names.
I found similar issue for butterKnife and took solution from there.
https://github.com/JakeWharton/butterknife/pull/117
Here is correct proguard rules:
```
-dontwarn icepick.**
-keep class **$$Icicle { *; }
-keepclasseswithmembernames class * {
    @icepick.* <fields>;
}
```

**Comment by frankiesardo** [comment]
Thanks
