### ISSUE TITLE
icepick and apt

### ISSUE THREAD

**Issue by kafji** [frankiesardo/icepick#54]
$$icepick class isn't generated if we use icepick and [android apt plugin](https://bitbucket.org/hvisser/android-apt).

Solution that I found is to change the dependency scope from `provided` to `apt`.
From:
```
compile 'frankiesardo:icepick:3.0.2'
provided 'frankiesardo:icepick-processor:3.0.2'
```
To:
```
compile 'frankiesardo:icepick:3.0.2'
apt 'frankiesardo:icepick-processor:3.0.2'
```

**Comment by frankiesardo** [comment]
If using android apt plugin, then all the `provided` dependencies should become `apt` dependencies. See also https://github.com/frankiesardo/auto-parcel/issues/17
