### ISSUE TITLE
Icepick is not working for me

### ISSUE THREAD

**Issue by anelrh26** [frankiesardo/icepick#56]
Hi Frankie,

Since I heard of "icepick" I wanted to add it, to my project. But, for some reason it's not working for me. Also I don't know where to ask for this, sorry if this is not the good place. I hope that you can help me.

I'm trying to save two properties in my activity

@Icicle String title;
@Icicle int position;

And my BaseActivity Iooks like this

       @Override
	public void onCreate(Bundle savedInstanceState) {
          super.onCreate(savedInstanceState);
        Icepick.restoreInstanceState(this, savedInstanceState);
	}

        @Override
	public void onSaveInstanceState(Bundle outState) {
	super.onSaveInstanceState(outState);
        Icepick.saveInstanceState(this, outState);
	}

But, when I rotate the device, the properties title and position are always null and ZERO

I added the library with gradle and also I pasted your suggestion for the proguard file. What I'm missing?

How can be sure if IcePick is saving the properties? Thanks

**Comment by fahimk** [comment]
Are you using the apt plugin? Try changing the word "provided" to "apt" in your gradle file. See this issue for more information:

https://github.com/frankiesardo/icepick/issues/54

**Comment by frankiesardo** [comment]
You need to provide a bit more context to help us help you.

As @fahimk says, first check that the generated classes are there. But if they weren't there you should probably have seen an exception. So my best guess is: are you actually changing the value of title and position somewhere in your code?

**Comment by anelrh26** [comment]
No, I'm not using the apt plugin. Actually the "apt" is not recognised by the gradle that I have :S

**Comment by anelrh26** [comment]
This is the debug

06-19 16:21:16.481    1907-1907/com.myapp D/Icepick﹕ Not found. Trying superclass com.myapp.ui.activities.BaseActivity
06-19 16:21:16.481    1907-1907/com.myapp D/Icepick﹕ Not found. Trying superclass android.support.v7.app.ActionBarActivity
06-19 16:21:16.481    1907-1907/com.myapp D/Icepick﹕ MISS: Reached framework class. Abandoning search.
06-19 16:21:17.145    1907-1907/com.myapp D/Icepick﹕ Not found. Trying superclass com.myapp.ui.activities.BaseActivity
06-19 16:21:17.145    1907-1907/com.myapp D/Icepick﹕ Not found. Trying superclass android.support.v7.app.ActionBarActivity
06-19 16:21:17.145    1907-1907/com.myapp D/Icepick﹕ MISS: Reached framework class. Abandoning search.
06-19 16:21:51.177    1907-1907/com.myapp D/Icepick﹕ Not found. Trying superclass com.myapp.ui.activities.BaseActivity
06-19 16:21:51.177    1907-1907/com.myapp D/Icepick﹕ Not found. Trying superclass android.support.v7.app.ActionBarActivity
06-19 16:21:51.177    1907-1907/com.myapp D/Icepick﹕ MISS: Reached framework class. Abandoning search.
06-19 16:21:51.261    1907-1907/com.myapp D/Icepick﹕ Not found. Trying superclass com.myapp.ui.activities.BaseActivity
06-19 16:21:51.261    1907-1907/com.myapp D/Icepick﹕ Not found. Trying superclass android.support.v7.app.ActionBarActivity
06-19 16:21:51.261    1907-1907/com.myapp D/Icepick﹕ MISS: Reached framework class. Abandoning search.

**Comment by frankiesardo** [comment]
That means that Icepick has not generated the classes to save and restore the state. Can you post your build.gradle file

**Comment by anelrh26** [comment]
Here it is http://pastie.org/10249054

**Comment by frankiesardo** [comment]
Try and use the same configuration that you use for dagger

**Comment by anelrh26** [comment]
I still not have the class generated :S

**Comment by anelrh26** [comment]
It's working now, you were right. Thank you so much

**Comment by oradkovsky** [comment]
Thank you, comment re 'apt' helped me to resolve similar issue.

**Comment by gastoncesarf** [comment]
@frankiesardo I am not using dagger, What should I do to configure the library?,I have the same problem that was described in this issue. (Note: my project has modules)
