### ISSUE TITLE
Exclude an activity from Icepick?

### ISSUE THREAD

**Issue by aeroperf** [frankiesardo/icepick#57]
Is there a way to exclude an activity (Settings, in my case) from being instantiated again? Upon a theme change, I use getActivity().recreate to swap themes, but then I have two instances of Settings activity and must hit the back button twice to remove them. This does not happen when I disable Icepick.

**Comment by frankiesardo** [comment]
It should not be instantiated again. That seems like a bug to me. Can you provide more details?

**Comment by frankiesardo** [comment]
Closing for now. If more details surface I'll reopen the issue
