### ISSUE TITLE
Incompatible with AndroidAnnotations?

### ISSUE THREAD

**Issue by NickThissen** [frankiesardo/icepick#60]
This seems like a great library because I hate the 'save/load instance state' boilerplate code.

I have found however that it does not work in combination with AndroidAnnotations. When I decorate an Activity with @EActivity attribute (and reference it using the underscore name in the manifest, eg "MainActivity_") then any fields decorated with @Icicle are no longer saved automatically.

Most likely the issue is that AndroidAnnotations generates the new class with the underscore name and icepick is not compatible with this?

Is there anything I can do to solve this?

**Comment by frankiesardo** [comment]
I'm not an expert of AA but it think it should generate an Activity that is subclass of your annotated @EActivity.

When saving/restoring Icepick already tries every superclass before giving up (you can see it here https://github.com/frankiesardo/icepick/blob/master/icepick/src/icepick/Icepick.java#L27-L49). You can call `Icepick.setDebug(true)` to get more verbose explanation.

**Comment by NickThissen** [comment]
I don't know where the problem lies exactly but I can't get it to work.

Here's a use case.

A simple MainActivity with two buttons and a TextView, the Textview displays a number and the buttons increase or decrease it. Number is stored using Icicle attribute.

	public class MainActivity extends AppCompatActivity
	{
		TextView txtNumber;
		Button btnIncr, btnDecr;

		@Icicle int number;

		@Override
		protected void onCreate(Bundle bundle)
		{
			super.onCreate(bundle);
			setContentView(R.layout.activity_main);

                        Icepick.restoreInstanceState(this, bundle);

			txtNumber = (TextView) findViewById(R.id.txtNumber);
			btnIncr = (Button) findViewById(R.id.btnIncr);
			btnDecr = (Button) findViewById(R.id.btnDecr);

			updateNumber(0);

			btnIncr.setOnClickListener(new View.OnClickListener()
			{
				@Override
				public void onClick(View v)
				{
					updateNumber(1);
				}
			});

			btnDecr.setOnClickListener(new View.OnClickListener()
			{
				@Override
				public void onClick(View v)
				{
					updateNumber(-1);
				}
			});
		}

		@Override
		public void onSaveInstanceState(Bundle bundle)
		{
			super.onSaveInstanceState(bundle);
			Icepick.saveInstanceState(this, bundle);
		}

		@Override
		public void onRestoreInstanceState(Bundle bundle)
		{
			super.onRestoreInstanceState(bundle);
			Icepick.restoreInstanceState(this, bundle);
		}

		private void updateNumber(int change)
		{
			number += change;
			txtNumber.setText(Integer.toString(number));
		}
	}

This works fine. Then add the @EActivity attribute to annotate it with AndroidAnnotations (and change the name to "MainActivity_" with the underscore in the manifest, and it stops working. Number is no longer maintained after (for example) an orientation change. Works fine without the attribute, no longer works with the attribute :(

**Comment by frankiesardo** [comment]
As I said, try turning debugging on to give me more info, otherwise it's hard for me to help you. Pasting the code from the generated `MainActivity_` might help as well.

**Comment by NickThissen** [comment]
It says it's trying superclass MainActivity but still can't find it:

	08-04 14:11:30.641  27157-27157/nl.nickthissen.tablayouttest D/Icepick﹕ Not found. Trying superclass nl.nickthissen.tablayouttest.MainActivity
	08-04 14:11:30.641  27157-27157/nl.nickthissen.tablayouttest D/Icepick﹕ Not found. Trying superclass android.support.v7.app.AppCompatActivity
	08-04 14:11:30.642  27157-27157/nl.nickthissen.tablayouttest D/Icepick﹕ MISS: Reached framework class. Abandoning search.


This is the generated MainActivity_


	package nl.nickthissen.tablayouttest;

	import android.app.Activity;
	import android.content.Context;
	import android.content.Intent;
	import android.os.Bundle;
	import android.view.KeyEvent;
	import android.view.View;
	import android.view.ViewGroup.LayoutParams;
	import org.androidannotations.api.SdkVersionHelper;
	import org.androidannotations.api.view.HasViews;
	import org.androidannotations.api.view.OnViewChangedNotifier;

	public final class MainActivity_
		extends MainActivity
		implements HasViews
	{

		private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

		@Override
		public void onCreate(Bundle savedInstanceState) {
			OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
			init_(savedInstanceState);
			super.onCreate(savedInstanceState);
			OnViewChangedNotifier.replaceNotifier(previousNotifier);
		}

		private void init_(Bundle savedInstanceState) {
		}

		@Override
		public void setContentView(int layoutResID) {
			super.setContentView(layoutResID);
			onViewChangedNotifier_.notifyViewChanged(this);
		}

		@Override
		public void setContentView(View view, LayoutParams params) {
			super.setContentView(view, params);
			onViewChangedNotifier_.notifyViewChanged(this);
		}

		@Override
		public void setContentView(View view) {
			super.setContentView(view);
			onViewChangedNotifier_.notifyViewChanged(this);
		}

		public static MainActivity_.IntentBuilder_ intent(Context context) {
			return new MainActivity_.IntentBuilder_(context);
		}

		public static MainActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
			return new MainActivity_.IntentBuilder_(fragment);
		}

		public static MainActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
			return new MainActivity_.IntentBuilder_(supportFragment);
		}

		@Override
		public boolean onKeyDown(int keyCode, KeyEvent event) {
			if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
				onBackPressed();
			}
			return super.onKeyDown(keyCode, event);
		}

		public static class IntentBuilder_ {

			private Context context_;
			private final Intent intent_;
			private android.app.Fragment fragment_;
			private android.support.v4.app.Fragment fragmentSupport_;

			public IntentBuilder_(Context context) {
				context_ = context;
				intent_ = new Intent(context, MainActivity_.class);
			}

			public IntentBuilder_(android.app.Fragment fragment) {
				fragment_ = fragment;
				context_ = fragment.getActivity();
				intent_ = new Intent(context_, MainActivity_.class);
			}

			public IntentBuilder_(android.support.v4.app.Fragment fragment) {
				fragmentSupport_ = fragment;
				context_ = fragment.getActivity();
				intent_ = new Intent(context_, MainActivity_.class);
			}

			public Intent get() {
				return intent_;
			}

			public MainActivity_.IntentBuilder_ flags(int flags) {
				intent_.setFlags(flags);
				return this;
			}

			public void start() {
				context_.startActivity(intent_);
			}

			public void startForResult(int requestCode) {
				if (fragmentSupport_!= null) {
					fragmentSupport_.startActivityForResult(intent_, requestCode);
				} else {
					if (fragment_!= null) {
						fragment_.startActivityForResult(intent_, requestCode);
					} else {
						if (context_ instanceof Activity) {
							((Activity) context_).startActivityForResult(intent_, requestCode);
						} else {
							context_.startActivity(intent_);
						}
					}
				}
			}

		}

	}

**Comment by frankiesardo** [comment]
So it is actually loading your MainActivity as you can see here.

`08-04 14:11:30.641  27157-27157 l.nickthissen.tablayouttest D/Icepick﹕ Not found. Trying superclass nl.nickthissen.tablayouttest.MainActivity`

The problem is there's no `MainActivity$$Icicle` class generated, which means your annotation processing setup has something wrong. Check that you're using the same qualifier for android-annotations and icepick (e.g. `provided` or `apt`). See also https://github.com/frankiesardo/icepick/issues/56

**Comment by NickThissen** [comment]
I have the following:

    compile 'frankiesardo:icepick:3.1.0'
    provided 'frankiesardo:icepick-processor:3.1.0'
    apt "org.androidannotations:androidannotations:3.0+"
    compile 'org.androidannotations:androidannotations-api:3.0+'

So you are saying 'provided' should be replaced with 'apt'? So it should be:

    compile 'frankiesardo:icepick:3.1.0'
    apt 'frankiesardo:icepick-processor:3.1.0'
    apt "org.androidannotations:androidannotations:3.0+"
    compile 'org.androidannotations:androidannotations-api:3.0+'

That doesn't change anything unfortunately.

**Comment by frankiesardo** [comment]
See if at least a `MainActivity$$Icicle` class is generated in your build directory. Doing a gradle clean might help.

**Comment by NickThissen** [comment]
Thanks, doing a clean helped, it is working now. 

Good to know about this 'provided' and 'apt' stuff, I have no clue what it's doing though...
