### ISSUE TITLE
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_51\bin\java.exe'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by adityasharma1912** [frankiesardo/icepick#62]
Information:Gradle tasks [:AbcApp:assembleDebug]
:AbcApp:preBuild UP-TO-DATE
:AbcApp:preDebugBuild UP-TO-DATE
:AbcApp:checkDebugManifest
:AbcApp:preReleaseBuild UP-TO-DATE
:android-support-v7-appcompat:compileLint
:android-support-v7-appcompat:copyReleaseLint UP-TO-DATE
:android-support-v7-appcompat:mergeReleaseProguardFiles UP-TO-DATE
:android-support-v7-appcompat:preBuild UP-TO-DATE
:android-support-v7-appcompat:preReleaseBuild UP-TO-DATE
:android-support-v7-appcompat:checkReleaseManifest
:android-support-v7-appcompat:prepareReleaseDependencies
:android-support-v7-appcompat:compileReleaseAidl UP-TO-DATE
:android-support-v7-appcompat:compileReleaseRenderscript UP-TO-DATE
:android-support-v7-appcompat:generateReleaseBuildConfig UP-TO-DATE
:android-support-v7-appcompat:generateReleaseAssets UP-TO-DATE
:android-support-v7-appcompat:mergeReleaseAssets UP-TO-DATE
:android-support-v7-appcompat:generateReleaseResValues UP-TO-DATE
:android-support-v7-appcompat:generateReleaseResources UP-TO-DATE
:android-support-v7-appcompat:packageReleaseResources UP-TO-DATE
:android-support-v7-appcompat:processReleaseManifest UP-TO-DATE
:android-support-v7-appcompat:processReleaseResources UP-TO-DATE
:android-support-v7-appcompat:generateReleaseSources UP-TO-DATE
:android-support-v7-appcompat:processReleaseJavaRes UP-TO-DATE
:android-support-v7-appcompat:compileReleaseJava UP-TO-DATE
:android-support-v7-appcompat:packageReleaseJar UP-TO-DATE
:android-support-v7-appcompat:compileReleaseNdk UP-TO-DATE
:android-support-v7-appcompat:packageReleaseJniLibs UP-TO-DATE
:android-support-v7-appcompat:packageReleaseLocalJar UP-TO-DATE
:android-support-v7-appcompat:packageReleaseRenderscript UP-TO-DATE
:android-support-v7-appcompat:bundleRelease UP-TO-DATE
:robodemolib:compileLint
:robodemolib:copyReleaseLint UP-TO-DATE
:robodemolib:mergeReleaseProguardFiles UP-TO-DATE
:robodemolib:preBuild UP-TO-DATE
:robodemolib:preReleaseBuild UP-TO-DATE
:robodemolib:checkReleaseManifest
:robodemolib:prepareReleaseDependencies
:robodemolib:compileReleaseAidl UP-TO-DATE
:robodemolib:compileReleaseRenderscript UP-TO-DATE
:robodemolib:generateReleaseBuildConfig UP-TO-DATE
:robodemolib:generateReleaseAssets UP-TO-DATE
:robodemolib:mergeReleaseAssets UP-TO-DATE
:robodemolib:generateReleaseResValues UP-TO-DATE
:robodemolib:generateReleaseResources UP-TO-DATE
:robodemolib:packageReleaseResources UP-TO-DATE
:robodemolib:processReleaseManifest UP-TO-DATE
:robodemolib:processReleaseResources UP-TO-DATE
:robodemolib:generateReleaseSources UP-TO-DATE
:robodemolib:processReleaseJavaRes UP-TO-DATE
:robodemolib:compileReleaseJava UP-TO-DATE
:robodemolib:packageReleaseJar UP-TO-DATE
:robodemolib:compileReleaseNdk UP-TO-DATE
:robodemolib:packageReleaseJniLibs UP-TO-DATE
:robodemolib:packageReleaseLocalJar UP-TO-DATE
:robodemolib:packageReleaseRenderscript UP-TO-DATE
:robodemolib:bundleRelease UP-TO-DATE
:AbcApp:prepareCD64AndroidSupportV7AppcompatUnspecifiedLibrary UP-TO-DATE
:AbcApp:prepareCD64RobodemolibUnspecifiedLibrary UP-TO-DATE
:AbcApp:prepareComAndroidSupportCardviewV72103Library UP-TO-DATE
:AbcApp:prepareComAndroidSupportRecyclerviewV72103Library UP-TO-DATE
:AbcApp:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:AbcApp:prepareComFacebookAndroidFacebookAndroidSdk410Library UP-TO-DATE
:AbcApp:prepareComFacebookFrescoDrawee061Library UP-TO-DATE
:AbcApp:prepareComFacebookFrescoFbcore061Library UP-TO-DATE
:AbcApp:prepareComFacebookFrescoFresco061Library UP-TO-DATE
:AbcApp:prepareComFacebookFrescoImagepipeline061Library UP-TO-DATE
:AbcApp:prepareComGoogleAndroidGmsPlayServicesAds750Library UP-TO-DATE
:AbcApp:prepareComGoogleAndroidGmsPlayServicesAnalytics750Library UP-TO-DATE
:AbcApp:prepareComGoogleAndroidGmsPlayServicesAppindexing750Library UP-TO-DATE
:AbcApp:prepareComGoogleAndroidGmsPlayServicesBase750Library UP-TO-DATE
:AbcApp:prepareComGoogleAndroidGmsPlayServicesLocation750Library UP-TO-DATE
:AbcApp:prepareComGoogleAndroidGmsPlayServicesMaps750Library UP-TO-DATE
:AbcApp:prepareDebugDependencies
:AbcApp:compileDebugAidl UP-TO-DATE
:AbcApp:compileDebugRenderscript UP-TO-DATE
:AbcApp:generateDebugBuildConfig UP-TO-DATE
:AbcApp:generateDebugAssets UP-TO-DATE
:AbcApp:mergeDebugAssets UP-TO-DATE
:AbcApp:generateDebugResValues UP-TO-DATE
:AbcApp:generateDebugResources UP-TO-DATE
:AbcApp:mergeDebugResources UP-TO-DATE
:AbcApp:processDebugManifest UP-TO-DATE
:AbcApp:processDebugResources UP-TO-DATE
:AbcApp:generateDebugSources UP-TO-DATE
:AbcApp:processDebugJavaRes UP-TO-DATE
:AbcApp:compileDebugJava UP-TO-DATE
:AbcApp:compileDebugNdk UP-TO-DATE
:AbcApp:compileDebugSources UP-TO-DATE
:AbcApp:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/nineoldandroids/animation/Animator$AnimatorListener;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting
Error:Execution failed for task ':AbcApp:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_51\bin\java.exe'' finished with non-zero exit value 1
Information:BUILD FAILED

**Comment by frankiesardo** [comment]
Look at #46

**Comment by adityasharma1912** [comment]
But this dependency is not processor dependency, hence i have to use "compile" keyword only.
I checked post  #46 earlier also.

Thanks for your quick reply, seeking further help from you.

**Comment by frankiesardo** [comment]
What do you mean by "this dependency is not processor dependency"? If you need further help please provide more info about your setup, version used, gradle.build file and what you're trying to accomplish. A stacktrace alone doesn't provide enough context.

**Comment by adityasharma1912** [comment]
My build.gradle is as follows : 

buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}
apply plugin: 'android'

repositories {
    jcenter()       // This is the default repo
    mavenCentral()  //  This is the Maven Central repo

}
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile 'com.android.support:recyclerview-v7:21.0.+'
    compile 'com.android.support:cardview-v7:21.0.+'
    compile project(':android-support-v7-appcompat')
    compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    compile 'com.google.android.gms:play-services-maps:7.5.0'
    compile 'com.google.android.gms:play-services-ads:7.5.0'
    compile 'com.google.android.gms:play-services-analytics:7.5.0'
    compile 'com.google.android.gms:play-services-location:7.5.0'
    compile 'com.google.android.gms:play-services-appindexing:7.5.0'
    compile files('libs/google-http-client-1.18.0-rc.jar')
    compile files('libs/google-http-client-android-1.18.0-rc.jar')
    compile project(':robodemolib')
    compile 'com.facebook.fresco:fresco:0.6.1+'
}

android {
    compileSdkVersion 21
    buildToolsVersion '22.0.1'

    dexOptions {
        preDexLibraries = false
        javaMaxHeapSize "4g"
    }
    compileOptions {
        encoding "UTF-8"
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    lintOptions {
        abortOnError false
    }
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        // Move the tests to tests/java,
        // tests/res, etc...
        instrumentTest.setRoot('tests')

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the main source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.

    }
}


*******************************************************************************************

i am trying to use facebook's fresco library to fetch and show images in my application using follwing code : 

<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/imageview_car"
            android:layout_width="130dp"
            android:layout_height="130dp"
            fresco:placeholderImage="@drawable/abc_ab_bottom_solid_dark_holo"
            fresco:roundedCornerRadius="2dp"/>

**Comment by frankiesardo** [comment]
I don't see `icepick` in your project dependencies, nor `clojars` in your repositories. Please follow the readme for installation

**Comment by adityasharma1912** [comment]
adding this lib only in build.gradle is giving this problem : 
compile 'com.facebook.fresco:fresco:0.6.1+'

readme for installation means??
I do not have any readme for this library installation...

**Comment by adityasharma1912** [comment]
my project has nothing to do with icepick, sorry.

**Comment by saurabhlahoti93** [comment]
## **Getting this error on making build by applying Proguard **
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by splm** [comment]
Remember to modify this part.
android {
    compileSdkVersion 21
    buildToolsVersion '23.0.0'
