### ISSUE TITLE
Proguard rule  breaks -repackageclasses

### ISSUE THREAD

**Issue by vivascu** [frankiesardo/icepick#63]
```-keepnames class * { @icepick.State *; }```
prevents proguard to execute 
```-repackageclasses 'k'```

If I remove the keepnames line  obfuscation runs as expected. And strangely it does not seem to affect the app. 

Could you suggest why this is happening and if I really need this line in the proguard rules ?

**Comment by SilkSama** [comment]
up

**Comment by frankiesardo** [comment]
It's probably not needed after all. I'll remove it from the readme.
