### ISSUE TITLE
project.clj bundled into apk two times

### ISSUE THREAD

**Issue by konmik** [frankiesardo/icepick#68]
3.1.0

apk\META-INF\leiningen\frankiesardo\icepick\project.clj 
apk\project.clj

**Comment by ultimate-deej** [comment]
Should it be there at all?

**Comment by frankiesardo** [comment]
Nah, it should have been excluded from the jar (see [here](https://github.com/frankiesardo/icepick/blob/master/icepick/project.clj#L16)). I'll make sure for the next release we get rid of it. No big harm for now.

**Comment by frankiesardo** [comment]
Fixed in the latest release
