### ISSUE TITLE
Unnecessary object instantiation

### ISSUE THREAD

**Issue by pushbit** [frankiesardo/icepick#69]
`Icepick.saveInstanceState` and `restoreInstanceState` are calling `safeGet` with a `new Injector.Object` (or `View`) instance, but that instance would only be used in the exceptional case that these methods are called with a class that doesn't have a `$$Icepick` companion class (developer error).

Would it be possible to move the `Injector.Object/View` instantiation to `safeGet` so that it is only instantiated when necessary?  It also appears that a single static instance could be used, since these classes are stateless no-ops.  This would help to minimise garbage collection and improve overall performance.

**Comment by frankiesardo** [comment]
Unless I'm mistaken otherwise allocating a new object during those two methods should have no impact on a third party user. Can you point me to any resource that say otherwise? We're not talking about `onPaint` methods, and if we blindly optimise for speed we loose in readability.

**Comment by pushbit** [comment]
I agree that in this particular case, the unused object allocation is unlikely to cause a significant negative impact.  But if this approach was taken across libraries and apps, it could build up to become a problem when many objects are allocated, not used, and then garbage collected (along with other used objects).  The official Android [Performance Tips][1] recommend this in the introduction and the *Avoid Creating Unnecessary Objects* section.

I also agree that readability can influence these types of situations, though in this case I think that readability could be virtually unaffected, perhaps even improved.  Instead of the second parameter to `safeGet` being `new Injector.{Object,View}<T>()`, it could refer to constants like `DEFAULT_OBJECT_INJECTOR` and `DEFAULT_VIEW_INJECTOR`.

[1]: https://developer.android.com/training/articles/perf-tips.html

**Comment by frankiesardo** [comment]
I agree with your point of view and just wanted to add that this is a low hanging fruit perfect for someone who wants to prepare a pull request and get involved in the repo.
