### ISSUE TITLE
emulator: WARNING: Requested RAM size of 1536MB is too large for your environment, and is reduced to 648MB. emulator: device fd:616 HAXM is not working and emulator runs in emulation mode emulator: The memory needed by this AVD exceeds the max specified in your HAXM configuration. emulator: AVD      RAM size = 648 MB emulator: HAXM max RAM size = 512 MB emulator: You might want to adjust your AVD RAM size and/or HAXM configuration to run in fast virt mode. Cannot set up guest memory 'pc.ram': Invalid argument

### ISSUE THREAD

**Issue by RAVIKUMARBG** [frankiesardo/icepick#74]
emulator: WARNING: Requested RAM size of 1536MB is too large for your environment, and is reduced to 648MB.
emulator: device fd:616
HAXM is not working and emulator runs in emulation mode
emulator: The memory needed by this AVD exceeds the max specified in your HAXM configuration.
emulator: AVD      RAM size = 648 MB
emulator: HAXM max RAM size = 512 MB
emulator: You might want to adjust your AVD RAM size and/or HAXM configuration to run in fast virt mode.
Cannot set up guest memory 'pc.ram': Invalid argument

**Comment by NeilDeshmukh** [comment]
-The memory needed by this AVD should not be exceeds the max specified in your HAXM configuration.
- It should be less than RAM set for HAMX.
- go to ~\\AppData\Local\Android\sdk\extras\intel\Hardware_Accelerated_Execution_Manager   \intelhamx_android.exe
- reinstall intel HAXM and set its RAM to 1024MB
- edit your AVD set its RAM to 768MB

and there u go.....build & run your application....
