### ISSUE TITLE
:app:transformClassesWithMultidexlistForDebug FAILED

### ISSUE THREAD

**Issue by patelanil2007** [frankiesardo/icepick#75]
Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't read [C:\Users\creative\AppData\Local\Android\sdk\build-tools\19.1.0\multidex\shrinkedAndroid.jar] (No such file or directory)

**Comment by ahmadriyal** [comment]
i am indian , i hav ebeen programming from 10 years and i couldn`t solve dis
do you know de way?
