### ISSUE TITLE
Ship Proguard rules in aar

### ISSUE THREAD

**Issue by vanniktech** [frankiesardo/icepick#77]
Is it possible to ship the proguard rules?

If you provide an AAR dependency you can ship them with `consumerProguardFiles`.

**Comment by frankiesardo** [comment]
Yes it is possible. I'm adding this to my todo list

**Comment by vanniktech** [comment]
Awesome. I just saw that you're not using Gradle as the buildsystem so I'm not sure how flexible you are. Otherwise with gradle it's super easy.

```groovy
defaultConfig {
        consumerProguardFiles 'proguard-rules.txt'
}
```

And then in the text file just simply put the normal proguard rules.

**Comment by vanniktech** [comment]
Personally I'm no longer interested in this and hence closing it. Thanks anyways :)
