### ISSUE TITLE
IcePick won't resolve in gradle

### ISSUE THREAD

**Issue by enyciaa** [frankiesardo/icepick#82]
Hi,

I'm having trouble getting IcePick from Clojar. Both these lines cause a failed to resolve error in gradle:

compile "frankiesardo:icepick:3.2.0"
compile "frankiesardo:icepick-processor:3.2.0"

However I did find an old version of the library that works:

compile 'com.github.frankiesardo:icepick:2.3.6'
provided 'com.github.frankiesardo:icepick-processor:2.3.6'

However this would involve using quite a dated version of the library. Is there any way round the error with the latest version of the library on Clojar?

Thanks!

**Comment by frankiesardo** [comment]
Hi have you added

```
repositories {
  maven {url "https://clojars.org/repo/"}
}
```

To your build.gradle file?

**Comment by enyciaa** [comment]
That did the trick! 

My bad for not reading properly...

**Comment by vladtamas** [comment]
Hi,

I'm having the same issue as described above. I added maven {url "https://clojars.org/repo/"} in repositories and compile 'frankiesardo:icepick:3.2.0' in dependencies. It works with older versions of icepick as described above.

**Comment by arekolek** [comment]
@vladtamas Make sure you add it to the right repositories section:

buildscript {
    repositories {
      // Here is no good
    }
}
repositories {
    // Here is good:
    maven { url 'https://clojars.org/repo' }
}

**Comment by MarinaEariel** [comment]
Seems to be working now.
