### ISSUE TITLE
Doesn't work with Dagger2

### ISSUE THREAD

**Issue by NitroG42** [frankiesardo/icepick#83]
I just added icepick on a project that uses Dagger2. (I use kotlin too but it shouldn't be a problem)
I have a fragment with a value I want to save, kinda like that : 
```
class MyFragment : Fragment() {
    @State
    var myValue: Float = 0f
    @Inject
    val networkApi: NetworkApi   

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Icepick.restoreInstanceState(this, savedInstanceState)
    }
    override fun onSaveInstanceState(outState: Bundle?) {
        super.onSaveInstanceState(outState)
        Icepick.saveInstanceState(this, outState)
    }
}
```

And when I build, I got this error :
`Error:Don't know how to put a my.package.NetworkApi inside a Bundle.`
But NetworkApi doesn't have the @State (and it's in an abstract class too...)
Is there something I'm missing ? I think there is somekind of a problem with dagger2 annotation and icepick's one.

**Comment by frankiesardo** [comment]
Can you reproduce it using Java? Try to narrow down the problem to a
minimal failing example

**Comment by NitroG42** [comment]
I tried with a fresh project in Java, it works, I converted it in Kotlin, it works too. 
I need to narrow down the error on my project. I'll comment here if I find the exact cause.

**Comment by NitroG42** [comment]
I looked more into this, and actually the problem comes from Kotlin and clojure, they definitelly doesn't work well together.
