### ISSUE TITLE
Gradle integration isn't working

### ISSUE THREAD

**Issue by Duna** [frankiesardo/icepick#90]
```
repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://clojars.org/repo/'}
}
```

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':library')
    compile 'com.android.support:multidex:1.0.1'
    compile "frankiesardo:icepick:3.1.0"
    provided "frankiesardo:icepick-processor:3.1.0"
}
```

Ant got the error: Error:Could not find frankiesardo:icepick:3.1.0.
Required by:
    ElephantMobile:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by shuufi** [comment]
Have this issue as well but the current version is now `3.2.0`

[From Clojars](https://clojars.org/frankiesardo/icepick-processor)

**Comment by frankiesardo** [comment]
Seems an isolated problem. Marking this as resolved unless further evidence
