### ISSUE TITLE
Differentiate INJECTORS cache hit of null vs not present

### ISSUE THREAD

**Issue by elihart** [frankiesardo/icepick#96]
`Icepick.getInjector` looks for an injector cache hit with
```
Injector var1 = (Injector)INJECTORS.get(var0);
        if(var1 != null) {
            if(debug) {
                Log.d("Icepick", "HIT: Cached in injector map.");
            }

            return var1;
        } 
```

The problem is that even if the Injectors map contains the value, but it is null, it is not considered a hit. Then the injector is looked up again.

We have a base fragment used across our app that applies icepick to all subclasses, but not all of those subclasses have saved state. In those cases Icepick constantly searches for the injector.

A simple `INJECTORS.contains` check would help this case and improve performance.

**Comment by frankiesardo** [comment]
Thanks

**Comment by elihart** [comment]
Thanks for fixing @frankiesardo! any plans to make a new release that includes this?
