### ISSUE TITLE
Raw java files included in our APK

### ISSUE THREAD

**Issue by RomainPiel** [frankiesardo/icepick#98]
Hi,
We're wondering why we're seeing some raw java files at the root of our apk under a folder `icepick`?
![screen shot 2017-03-29 at 17 59 02](https://cloud.githubusercontent.com/assets/464320/24466618/6d0fb69e-14a9-11e7-8cb1-b685e24af00a.png)
Is that used? Can it be excluded?

**Comment by frankiesardo** [comment]
Hi this is part of the library and it must be included as it does the runtime resolution for State manipulation.

**Comment by RomainPiel** [comment]
@frankiesardo thanks for the quick reply. Interesting, I see the compiled source inside the dex as well. So both of them are used?
I'd love to know how that whole thing work, looks interesting!
